options:
  enable-ipv6:
    default: False
    type: boolean
    description: |
      Enable BIRD's IPv6 support. Requires that all nodes with
      this charm installed on them have global scope IPv6
      addresses.
